//! Onboarding an EGS unit: the OTP, the two certificates, and the renewal.
//!
//! # The flow ZATCA specifies
//!
//! ```text
//!   Fatoora portal ──► the taxpayer logs in and generates a 6-digit OTP
//!                      (theirs, ours only in passing, ~1 hour)
//!            │
//!            ▼
//!   1  generate a key pair and a CSR                     zatca::csr
//!   2  POST /compliance          OTP header + the CSR ──► compliance CSID
//!   3  POST /compliance/invoices one of each document ──► checks passed
//!   4  POST /production/csids    the request id       ──► production CSID
//!            │
//!            ▼
//!   from here on, clearance and reporting authenticate with the production CSID
//! ```
//!
//! **Steps 2 and 4 are separate calls here, and separate on purpose.** Step 3
//! sits between them, needs every sample document signed with the compliance
//! certificate, and is the piece this build cannot finish — see
//! [`ComplianceChecks`]. Hiding both certificate requests inside one function
//! would hide that.
//!
//! # What is stored, and where
//!
//! Three secrets, sealed, in `module_secret` — never the event log, which is
//! immutable and replayed, and never `proj_tax_sa`, which is rebuilt:
//!
//! | key | what |
//! |---|---|
//! | `tax_sa.zatca.key` | the private key. **Never leaves this process.** |
//! | `tax_sa.zatca.compliance` | the compliance CSID, and the request id step 4 needs |
//! | `tax_sa.zatca.production` | the production CSID — what signs and submits real invoices |
//!
//! What goes in the **log** is the fact that a certificate was issued, with its
//! subject, serial and validity. That is what answers "which certificate signed
//! this invoice?" years later, and none of it is secret.
//!
//! # The order of operations, which matters
//!
//! The key is sealed **before** the network call. A call that succeeds and then
//! fails to store leaves a certificate bound to a key nobody has — unrecoverable
//! except by onboarding again with a fresh OTP. A key stored before a call that
//! fails is an orphan that the next attempt overwrites.

use erp_eventlog::{Metadata, SealingKey};
use erp_tenant::TenantDb;
use erp_types::Timestamp;
use serde::{Deserialize, Serialize};

use base64::Engine as _;

use super::csr::{Environment, Generated, Unit};
use super::wire::Unanswered;

const B64: base64::engine::general_purpose::GeneralPurpose =
    base64::engine::general_purpose::STANDARD;

/// Where the private key is sealed.
pub const KEY_SECRET: &str = "tax_sa.zatca.key";
/// Where the compliance CSID is sealed.
pub const COMPLIANCE_SECRET: &str = "tax_sa.zatca.compliance";
/// Where the production CSID is sealed. **The one that signs real invoices.**
pub const PRODUCTION_SECRET: &str = "tax_sa.zatca.production";

/// The one-time password from the Fatoora portal.
///
/// Six digits, valid for about an hour, generated by the taxpayer while logged
/// in as themselves. It is the only proof ZATCA gets that the person asking for
/// a certificate is the person who owns the VAT number — so it is never stored,
/// never logged, and never put in an event.
#[derive(Clone, PartialEq, Eq)]
pub struct Otp(String);

impl std::fmt::Debug for Otp {
    /// Withheld even from a panic message. An OTP in a log is a certificate
    /// somebody else can obtain for an hour.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Otp(<withheld>)")
    }
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[error("a Fatoora OTP is six digits")]
pub struct NotAnOtp;

impl std::str::FromStr for Otp {
    type Err = NotAnOtp;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let trimmed = s.trim();
        if trimmed.len() == 6 && trimmed.chars().all(|c| c.is_ascii_digit()) {
            return Ok(Self(trimmed.to_owned()));
        }
        Err(NotAnOtp)
    }
}

impl Otp {
    /// The value for the `OTP` header. The only place it is readable.
    #[must_use]
    pub fn header(&self) -> &str {
        &self.0
    }
}

/// The credentials ZATCA issues, and the request id the next step needs.
#[derive(Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Csid {
    /// The certificate, base64. The username half of the basic auth.
    pub token: String,
    /// The password half.
    pub secret: String,
    /// ZATCA's id for the request that produced this. The production call
    /// quotes the **compliance** one.
    pub request_id: String,
}

impl std::fmt::Debug for Csid {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Csid")
            .field("token", &format_args!("{} chars", self.token.len()))
            .field("secret", &"<withheld>")
            .field("request_id", &self.request_id)
            .finish()
    }
}

impl Csid {
    /// The `Authorization` header: basic auth, token as the user and secret as
    /// the password, exactly as ZATCA's API expects.
    #[must_use]
    pub fn authorization(&self) -> String {
        format!(
            "Basic {}",
            B64.encode(format!("{}:{}", self.token, self.secret))
        )
    }

    /// The certificate inside the token.
    ///
    /// # Two encodings, and no way to tell from the documentation
    ///
    /// `binarySecurityToken` is base64 — of the DER in some of ZATCA's
    /// examples and of the PEM body in others, which are the same bytes at one
    /// or two removes. Both are accepted here because both are unambiguous:
    /// DER starts with a `SEQUENCE` tag and base64 text does not.
    ///
    /// **Worth confirming against the sandbox on a deployment's first
    /// onboarding**, and the reason this returns which one it found rather than
    /// swallowing it.
    pub fn certificate(&self) -> Result<openssl::x509::X509, OnboardError> {
        let decoded = B64
            .decode(self.token.trim())
            .map_err(|e| OnboardError::Certificate(e.to_string()))?;

        // DER, if it looks like DER.
        if decoded.first() == Some(&0x30)
            && let Ok(certificate) = openssl::x509::X509::from_der(&decoded)
        {
            return Ok(certificate);
        }

        // Otherwise it is the PEM body, with or without its armour.
        let text =
            String::from_utf8(decoded).map_err(|e| OnboardError::Certificate(e.to_string()))?;
        let pem = if text.contains("-----BEGIN") {
            text
        } else {
            format!(
                "-----BEGIN CERTIFICATE-----\n{}\n-----END CERTIFICATE-----\n",
                text.trim()
            )
        };
        openssl::x509::X509::from_pem(pem.as_bytes())
            .map_err(|e| OnboardError::Certificate(e.to_string()))
    }
}

/// What ZATCA answers a certificate request with.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CsidResponse {
    #[serde(default, rename = "requestID")]
    pub request_id: Option<serde_json::Value>,
    /// `ISSUED`, `PENDING` or `REJECTED`.
    #[serde(default, rename = "dispositionMessage")]
    pub disposition: Option<String>,
    #[serde(default, rename = "binarySecurityToken")]
    pub token: Option<String>,
    #[serde(default)]
    pub secret: Option<String>,
    #[serde(default)]
    pub errors: Option<serde_json::Value>,
}

impl CsidResponse {
    /// The credentials, or why there are none.
    ///
    /// `PENDING` is a refusal here rather than something to poll: ZATCA returns
    /// it when a human at the authority has to look at the request, which is
    /// hours or days, not a retry loop.
    pub fn issued(self) -> Result<Csid, OnboardError> {
        // ZATCA leaves `dispositionMessage` out entirely on some refusals and
        // puts everything in `errors` — confirmed against the live simulation
        // environment, which answers an invalid OTP that way. An empty
        // disposition rendered into a message reads as a blank pair of
        // brackets, so it says what it is instead.
        let disposition = self
            .disposition
            .filter(|d| !d.trim().is_empty())
            .unwrap_or_else(|| "no disposition".to_owned());
        let (Some(token), Some(secret)) = (self.token, self.secret) else {
            return Err(OnboardError::NotIssued {
                disposition,
                detail: self.errors.map(|e| e.to_string()).unwrap_or_default(),
            });
        };
        if !disposition.eq_ignore_ascii_case("ISSUED") {
            return Err(OnboardError::NotIssued {
                disposition,
                detail: self.errors.map(|e| e.to_string()).unwrap_or_default(),
            });
        }

        Ok(Csid {
            token,
            secret,
            // A number in the JSON, a string everywhere it is used. Normalised
            // here so the production call cannot quote it in the wrong shape.
            request_id: match self.request_id {
                Some(serde_json::Value::String(s)) => s,
                Some(value) => value.to_string(),
                None => String::new(),
            },
        })
    }
}

/// The body of a compliance CSID request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComplianceRequest {
    /// The CSR, base64.
    pub csr: String,
}

/// The body of a production CSID request.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductionRequest {
    #[serde(rename = "compliance_request_id")]
    pub compliance_request_id: String,
}

/// The calls onboarding makes, which are the ones that need a socket.
///
/// Separate from [`Submitter`](super::wire::Submitter) because they are a
/// separate authority: these authenticate with an OTP or the compliance CSID,
/// that one with the production CSID, and a deployment may well have the second
/// working while the first is still being arranged.
#[async_trait::async_trait]
pub trait Registrar: Send + Sync + std::fmt::Debug {
    /// `POST /compliance`, with the OTP in a header.
    async fn compliance_csid(
        &self,
        environment: Environment,
        otp: &Otp,
        request: &ComplianceRequest,
    ) -> Result<CsidResponse, Unanswered>;

    /// `POST /compliance/invoices` — one sample document, authenticated with
    /// the compliance CSID.
    ///
    /// ZATCA answers with the same validation results as a clearance call, so
    /// the answer is a [`Verdict`]: the document passed, or it did not and the
    /// errors say why.
    async fn check_compliance(
        &self,
        environment: Environment,
        compliance: &Csid,
        submission: &super::wire::Submission,
    ) -> Result<super::wire::Verdict, Unanswered>;

    /// `POST /production/csids`, authenticated with the compliance CSID.
    async fn production_csid(
        &self,
        environment: Environment,
        compliance: &Csid,
        request: &ProductionRequest,
    ) -> Result<CsidResponse, Unanswered>;

    /// `PATCH /production/csids`, authenticated with the production CSID and a
    /// fresh OTP. A certificate lasts five years and this is how it is replaced
    /// without a new key.
    async fn renew_csid(
        &self,
        environment: Environment,
        production: &Csid,
        otp: &Otp,
        request: &ComplianceRequest,
    ) -> Result<CsidResponse, Unanswered>;
}

/// Which certificate this is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Stage {
    /// Issued against an OTP. It can only submit compliance documents.
    Compliance,
    /// Issued against a passed compliance check. **The one that clears real
    /// invoices.**
    Production,
}

impl Stage {
    pub const ALL: [Self; 2] = [Self::Compliance, Self::Production];

    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Compliance => "compliance",
            Self::Production => "production",
        }
    }

    /// Where this stage's credentials are sealed.
    #[must_use]
    pub const fn secret_key(self) -> &'static str {
        match self {
            Self::Compliance => COMPLIANCE_SECRET,
            Self::Production => PRODUCTION_SECRET,
        }
    }
}

impl std::str::FromStr for Stage {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::ALL
            .into_iter()
            .find(|stage| stage.as_str() == s)
            .ok_or_else(|| format!("unknown onboarding stage {s:?}"))
    }
}

#[derive(Debug, thiserror::Error)]
pub enum OnboardError {
    #[error(transparent)]
    Csr(#[from] super::csr::CsrError),
    /// ZATCA answered, and the answer was not a certificate.
    #[error("ZATCA did not issue a certificate ({disposition}): {detail}")]
    NotIssued { disposition: String, detail: String },
    /// ZATCA did not answer, so nothing was decided and nothing was stored.
    ///
    /// **Named by step.** Onboarding makes four calls and all four fail the
    /// same way, so an error that does not say which one leaves somebody
    /// bisecting a flow that talked to a tax authority — which is exactly how
    /// the first live run of this was misdiagnosed as a broken client when the
    /// certificate had in fact been issued and the *compliance check* was what
    /// answered strangely.
    #[error("{step}: {source}")]
    Unanswered {
        step: &'static str,
        #[source]
        source: Unanswered,
    },
    #[error("the certificate ZATCA returned could not be read: {0}")]
    Certificate(String),
    /// **The certificate is not for our key.** Either the wrong CSR was sent or
    /// the wrong key was loaded, and either way every signature made with it
    /// would be rejected — silently, at clearance.
    #[error("the certificate ZATCA returned does not match the private key held for this tenant")]
    KeyMismatch,
    /// The production certificate was asked for before there was a compliance
    /// one to ask with.
    #[error("this tenant has no {0} certificate yet")]
    NotYet(&'static str),
    #[error(transparent)]
    Secret(#[from] erp_eventlog::SecretError),
    #[error(transparent)]
    Command(#[from] erp_tenant::CommandError<crate::TaxError>),
    #[error(transparent)]
    Pool(#[from] erp_tenant::PoolError),
    #[error(transparent)]
    Database(#[from] sqlx::Error),
}

/// What a certificate turned out to be, once it was read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Issued {
    pub stage: Stage,
    pub environment: Environment,
    pub request_id: String,
    /// The certificate's subject, as one line.
    pub subject: String,
    /// Its serial number, in hex. What ZATCA's support desk asks for.
    pub serial: String,
    pub not_before: String,
    pub not_after: String,
}

/// The three things every onboarding call needs, so none of them takes eight
/// arguments.
///
/// The database, the key that seals what comes back, and the thing that talks to
/// ZATCA. A caller constructs one and runs whichever steps that tenant is due.
#[derive(Debug)]
pub struct Onboarder<'a> {
    db: &'a TenantDb,
    sealing: &'a SealingKey,
    registrar: &'a dyn Registrar,
}

impl<'a> Onboarder<'a> {
    #[must_use]
    pub fn new(db: &'a TenantDb, sealing: &'a SealingKey, registrar: &'a dyn Registrar) -> Self {
        Self {
            db,
            sealing,
            registrar,
        }
    }

    /// **Step 1 and 2.** Generates the key and the request, and exchanges the
    /// OTP for a compliance certificate.
    ///
    /// The key is sealed before the call, so a certificate is never issued
    /// against a key this tenant no longer has.
    pub async fn onboard(
        &self,
        unit: &Unit,
        environment: Environment,
        otp: &Otp,
        at: Timestamp,
        metadata: &Metadata,
    ) -> Result<Issued, OnboardError> {
        let csr = begin(self.db, self.sealing, unit, environment).await?;

        let response = self
            .registrar
            .compliance_csid(environment, otp, &ComplianceRequest { csr })
            .await
            .map_err(|source| OnboardError::Unanswered {
                step: "requesting a compliance certificate",
                source,
            })?;

        accept_certificate(
            self.db,
            self.sealing,
            Stage::Compliance,
            environment,
            &response.issued()?,
            at,
            metadata,
        )
        .await
    }

    /// **Step 3.** Proves the solution can produce every document type it
    /// declared.
    ///
    /// One sample of each — six for a unit that issues both kinds — signed with
    /// the **compliance** certificate and submitted to `/compliance/invoices`.
    /// ZATCA will not issue a production certificate until they all pass, so
    /// this runs between [`Self::onboard`] and [`Self::go_live`].
    ///
    /// The samples are invented and their chain is thrown away: see
    /// [`samples`](super::samples). Nothing here touches the tenant's real
    /// counter, which has not started yet and must start at one when it does.
    pub async fn pass_compliance_checks(
        &self,
        registration: &crate::taxpayer::Registration,
        unit: &Unit,
        environment: Environment,
        at: Timestamp,
    ) -> Result<ComplianceChecks, OnboardError> {
        let compliance = credentials(self.db, self.sealing, Stage::Compliance)
            .await?
            .ok_or(OnboardError::NotYet("compliance"))?;
        let key = private_key(self.db, self.sealing)
            .await?
            .ok_or(OnboardError::NotYet("key"))?;

        let certificate = compliance.certificate()?;
        let signer = super::signing::Signer::new(&key, &certificate)
            .map_err(|e| OnboardError::Certificate(e.to_string()))?;

        let mut checks = ComplianceChecks {
            submitted: 0,
            passed: 0,
            failures: Vec::new(),
        };

        for (number, submission) in compliance_submissions(registration, unit, &signer, at)? {
            let verdict = self
                .registrar
                .check_compliance(environment, &compliance, &submission)
                .await
                .map_err(|source| OnboardError::Unanswered {
                    step: "submitting a compliance document",
                    source,
                })?;

            checks.submitted += 1;
            match verdict {
                super::wire::Verdict::Accepted { .. } => checks.passed += 1,
                super::wire::Verdict::Refused { errors } => checks.failures.push((number, errors)),
            }
        }

        Ok(checks)
    }

    /// **Step 4.** Exchanges a compliance certificate for the production one.
    ///
    /// ZATCA answers this only once the unit has passed the compliance checks
    /// with the compliance certificate — see [`ComplianceChecks`]. Calling it
    /// too early is a refusal from ZATCA, which arrives here as
    /// [`NotIssued`](OnboardError::NotIssued) rather than as anything this build
    /// tries to interpret.
    pub async fn go_live(
        &self,
        environment: Environment,
        at: Timestamp,
        metadata: &Metadata,
    ) -> Result<Issued, OnboardError> {
        let compliance = credentials(self.db, self.sealing, Stage::Compliance)
            .await?
            .ok_or(OnboardError::NotYet("compliance"))?;

        let response = self
            .registrar
            .production_csid(
                environment,
                &compliance,
                &ProductionRequest {
                    compliance_request_id: compliance.request_id.clone(),
                },
            )
            .await
            .map_err(|source| OnboardError::Unanswered {
                step: "requesting a production certificate",
                source,
            })?;

        accept_certificate(
            self.db,
            self.sealing,
            Stage::Production,
            environment,
            &response.issued()?,
            at,
            metadata,
        )
        .await
    }

    /// Replaces a production certificate that is running out, keeping the key.
    ///
    /// A new key would invalidate nothing already signed — the old certificate
    /// stays valid for what it covered — but it would mean two keys to keep, so
    /// the renewal signs a fresh request with the key that is already stored.
    pub async fn renew(
        &self,
        unit: &Unit,
        environment: Environment,
        otp: &Otp,
        at: Timestamp,
        metadata: &Metadata,
    ) -> Result<Issued, OnboardError> {
        let production = credentials(self.db, self.sealing, Stage::Production)
            .await?
            .ok_or(OnboardError::NotYet("production"))?;
        let key = private_key(self.db, self.sealing)
            .await?
            .ok_or(OnboardError::NotYet("key"))?;

        let generated = super::csr::renew(unit, environment, &key)?;
        let response = self
            .registrar
            .renew_csid(
                environment,
                &production,
                otp,
                &ComplianceRequest {
                    csr: generated.csr_for_zatca(),
                },
            )
            .await
            .map_err(|source| OnboardError::Unanswered {
                step: "requesting a production certificate",
                source,
            })?;

        accept_certificate(
            self.db,
            self.sealing,
            Stage::Production,
            environment,
            &response.issued()?,
            at,
            metadata,
        )
        .await
    }
}

/// **Step 1 on its own**: generate the key pair, seal it, and hand back the
/// request.
///
/// # Why this is callable without a [`Registrar`]
///
/// Because onboarding is a once-per-tenant act with a human in the middle — the
/// taxpayer has to log in to Fatoora and read an OTP off a screen — and the two
/// halves are naturally separable. An operator can take this CSR, submit it with
/// `curl`, and paste what comes back into [`accept_certificate`].
///
/// That is not a workaround for the missing transport. It is the path a
/// deployment falls back to **when the automated one breaks**, which for a
/// once-per-tenant act with an hour-long credential is worth having either way.
///
/// Calling it twice generates a new key and discards the old one, which is right
/// as long as no certificate has been issued yet — and destructive afterwards.
/// [`reached`] is what a caller checks first.
pub async fn begin(
    db: &TenantDb,
    sealing: &SealingKey,
    unit: &Unit,
    environment: Environment,
) -> Result<String, OnboardError> {
    let generated = super::csr::generate(unit, environment)?;
    seal_key(db, sealing, &generated).await?;
    Ok(generated.csr_for_zatca())
}

/// **The other half**: take a certificate ZATCA issued, check it, and store it.
///
/// Checks it is **for the key this tenant holds** before anything is stored. A
/// certificate over somebody else's key is not a smaller problem than no
/// certificate: every signature made with it is rejected at clearance, on an
/// invoice a customer is waiting for, with an error that says nothing about why.
pub async fn accept_certificate(
    db: &TenantDb,
    sealing: &SealingKey,
    stage: Stage,
    environment: Environment,
    csid: &Csid,
    at: Timestamp,
    metadata: &Metadata,
) -> Result<Issued, OnboardError> {
    let key = private_key(db, sealing)
        .await?
        .ok_or(OnboardError::NotYet("key"))?;
    let issued = accept(csid, &key, stage, environment)?;

    store(db, sealing, stage, csid).await?;
    record(db, &issued, at, metadata).await?;
    Ok(issued)
}

/// The compliance documents, built, chained and signed — ready to submit.
///
/// Separated from [`Onboarder::pass_compliance_checks`] because everything
/// here is decidable without a database or a network, and because it is the
/// part worth running against ZATCA on its own: the driver is a loop, and this
/// is the code that has to be right.
pub fn compliance_submissions(
    registration: &crate::taxpayer::Registration,
    unit: &Unit,
    signer: &super::signing::Signer,
    at: Timestamp,
) -> Result<Vec<(String, super::wire::Submission)>, OnboardError> {
    let mut submissions = Vec::new();
    // **The chain is built as it goes**, because each document points at the
    // hash of the one before it and that hash is only known once it has been
    // rendered.
    let mut previous: Option<(i64, String)> = None;

    for mut document in super::samples::compliance_documents(registration, unit, at) {
        document.link = match &previous {
            Some((icv, hash)) => super::Link::after(*icv, hash),
            None => super::Link::first(),
        };

        let canonical =
            super::ubl::render(&document).map_err(|e| OnboardError::Certificate(e.to_string()))?;
        let hash = super::chain::invoice_hash(&canonical);
        previous = Some((document.link.icv, hash.clone()));

        let signature = signer
            .sign(&canonical, &hash, at)
            .map_err(|e| OnboardError::Certificate(e.to_string()))?;
        let qr = signature
            .qr(
                &document.seller.name,
                &document.seller.vat_number,
                &document.issued_at.format(super::QR_TIME).to_string(),
                &super::amount(document.totals.gross),
                &super::amount(document.totals.tax),
                &hash,
            )
            .map_err(|e| OnboardError::Certificate(e.to_string()))?;

        let submitted = super::ubl::signed(
            &document,
            &super::ubl::Enveloped {
                extensions: &signature.extensions,
                qr: &qr,
            },
        )
        .map_err(|e| OnboardError::Certificate(e.to_string()))?;

        submissions.push((
            document.number.clone(),
            super::wire::Submission {
                invoice_hash: hash,
                uuid: document.uuid.to_string(),
                invoice: B64.encode(super::ubl::with_declaration(&submitted)),
            },
        ));
    }

    Ok(submissions)
}

/// What the compliance checks found.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ComplianceChecks {
    /// How many documents were submitted.
    pub submitted: usize,
    /// How many ZATCA accepted. Anything less than `submitted` means the
    /// solution cannot go to production yet.
    pub passed: usize,
    /// What it said about the ones it refused, with the document each belongs
    /// to — the whole point of running these before a real invoice exists.
    pub failures: Vec<(String, Vec<super::wire::Remark>)>,
}

impl ComplianceChecks {
    /// Whether every document passed, which is what [`Onboarder::go_live`]
    /// needs to be true before ZATCA will answer it.
    #[must_use]
    pub const fn all_passed(&self) -> bool {
        self.submitted > 0 && self.passed == self.submitted
    }
}

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------

/// The production credentials, for signing and submitting. `None` until the
/// tenant has been through step 4.
pub async fn production(db: &TenantDb, sealing: &SealingKey) -> Result<Option<Csid>, OnboardError> {
    credentials(db, sealing, Stage::Production).await
}

/// The credentials for one stage.
pub async fn credentials(
    db: &TenantDb,
    sealing: &SealingKey,
    stage: Stage,
) -> Result<Option<Csid>, OnboardError> {
    let mut conn = db.acquire().await?;
    let found = erp_eventlog::secrets::get(&mut conn, sealing, stage.secret_key()).await?;
    drop(conn);

    found
        .map(|bytes| {
            serde_json::from_slice(&bytes)
                .map_err(|e| OnboardError::Certificate(format!("stored credentials: {e}")))
        })
        .transpose()
}

/// The private key, for signing. Never leaves the process.
pub async fn private_key(
    db: &TenantDb,
    sealing: &SealingKey,
) -> Result<Option<Vec<u8>>, OnboardError> {
    let mut conn = db.acquire().await?;
    let found = erp_eventlog::secrets::get(&mut conn, sealing, KEY_SECRET).await?;
    drop(conn);
    Ok(found)
}

/// Which stages this tenant has reached, without unsealing anything.
///
/// A status endpoint has to answer "is this tenant onboarded?" and must not be
/// able to read the key to do it.
pub async fn reached(db: &TenantDb) -> Result<Vec<Stage>, OnboardError> {
    let mut conn = db.read().await?;
    let mut found = Vec::new();
    for stage in Stage::ALL {
        if erp_eventlog::secrets::exists(&mut conn, stage.secret_key()).await? {
            found.push(stage);
        }
    }
    drop(conn);
    Ok(found)
}

async fn seal_key(
    db: &TenantDb,
    sealing: &SealingKey,
    generated: &Generated,
) -> Result<(), OnboardError> {
    let mut conn = db.acquire().await?;
    erp_eventlog::secrets::put(&mut conn, sealing, KEY_SECRET, &generated.private_key_pem).await?;
    drop(conn);
    Ok(())
}

async fn store(
    db: &TenantDb,
    sealing: &SealingKey,
    stage: Stage,
    csid: &Csid,
) -> Result<(), OnboardError> {
    let encoded = serde_json::to_vec(csid)
        .map_err(|e| OnboardError::Certificate(format!("storing credentials: {e}")))?;
    let mut conn = db.acquire().await?;
    erp_eventlog::secrets::put(&mut conn, sealing, stage.secret_key(), &encoded).await?;
    drop(conn);
    Ok(())
}

/// Reads the certificate, and **checks it is ours**.
///
/// The public key in the certificate has to be the public key of the private key
/// this tenant holds. If it is not, every signature made with it is rejected —
/// at clearance, on an invoice a customer is waiting for, with an error that
/// says nothing about why.
fn accept(
    csid: &Csid,
    private_key_pem: &[u8],
    stage: Stage,
    environment: Environment,
) -> Result<Issued, OnboardError> {
    let certificate = csid.certificate()?;

    let ours = openssl::ec::EcKey::private_key_from_pem(private_key_pem)
        .and_then(openssl::pkey::PKey::from_ec_key)
        .map_err(|e| OnboardError::Certificate(e.to_string()))?;
    let theirs = certificate
        .public_key()
        .map_err(|e| OnboardError::Certificate(e.to_string()))?;
    if !theirs.public_eq(&ours) {
        return Err(OnboardError::KeyMismatch);
    }

    Ok(Issued {
        stage,
        environment,
        request_id: csid.request_id.clone(),
        subject: certificate
            .subject_name()
            .entries()
            .filter_map(|entry| {
                let name = entry.object().nid().short_name().ok()?;
                let value = entry.data().to_string().ok()?;
                Some(format!("{name}={value}"))
            })
            .collect::<Vec<_>>()
            .join(", "),
        serial: certificate
            .serial_number()
            .to_bn()
            .and_then(|bn| bn.to_hex_str().map(|hex| hex.to_string()))
            .unwrap_or_default(),
        not_before: certificate.not_before().to_string(),
        not_after: certificate.not_after().to_string(),
    })
}

async fn record(
    db: &TenantDb,
    issued: &Issued,
    at: Timestamp,
    metadata: &Metadata,
) -> Result<(), OnboardError> {
    crate::commands::record_csid(db, issued, at, metadata).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn an_otp_is_six_digits_and_nothing_else() {
        assert!("123456".parse::<Otp>().is_ok());
        assert_eq!(
            "  123456 ".parse::<Otp>().map(|o| o.header().to_owned()),
            Ok("123456".to_owned())
        );
        for bad in ["12345", "1234567", "12345a", "", "  "] {
            assert_eq!(bad.parse::<Otp>(), Err(NotAnOtp), "{bad:?} was accepted");
        }
    }

    /// An OTP in a log is a certificate somebody else can obtain for an hour.
    #[test]
    fn neither_the_otp_nor_the_secret_appears_in_debug_output() {
        let otp: Otp = "654321".parse().expect("valid");
        assert!(!format!("{otp:?}").contains("654321"), "{otp:?}");

        let csid = Csid {
            token: "dG9rZW4=".to_owned(),
            secret: "s3cr3t".to_owned(),
            request_id: "1234".to_owned(),
        };
        let shown = format!("{csid:?}");
        assert!(!shown.contains("s3cr3t"), "{shown}");
        assert!(shown.contains("1234"), "the request id is not a secret");
    }

    #[test]
    fn the_authorization_header_is_the_token_and_the_secret() {
        let csid = Csid {
            token: "token".to_owned(),
            secret: "secret".to_owned(),
            request_id: "1".to_owned(),
        };
        let header = csid.authorization();
        let encoded = header.strip_prefix("Basic ").expect("basic auth");
        assert_eq!(
            String::from_utf8(B64.decode(encoded).expect("base64")).expect("utf-8"),
            "token:secret"
        );
    }

    #[test]
    fn a_response_without_a_certificate_is_not_one() {
        let pending = CsidResponse {
            disposition: Some("PENDING".to_owned()),
            token: Some("dG9rZW4=".to_owned()),
            secret: Some("s".to_owned()),
            ..CsidResponse::default()
        };
        assert!(matches!(
            pending.issued(),
            Err(OnboardError::NotIssued { .. })
        ));

        let rejected = CsidResponse {
            disposition: Some("REJECTED".to_owned()),
            errors: Some(serde_json::json!(["the OTP has expired"])),
            ..CsidResponse::default()
        };
        let Err(OnboardError::NotIssued { detail, .. }) = rejected.issued() else {
            panic!("a rejection is not an issue");
        };
        assert!(detail.contains("expired"), "{detail}");
    }

    /// ZATCA has answered with the request id as a number and as a string.
    /// **Recorded from ZATCA's live simulation environment.** An invalid OTP
    /// comes back with no `dispositionMessage` at all and everything in
    /// `errors`, which an earlier version of this rendered as an empty pair of
    /// brackets.
    #[test]
    fn a_refusal_with_no_disposition_still_says_what_happened() {
        let body = r#"{"errors":[{"code":"Invalid-OTP","message":"The provided OTP is invalid"}]}"#;
        let parsed: CsidResponse = serde_json::from_str(body).expect("reads");
        let Err(OnboardError::NotIssued {
            disposition,
            detail,
        }) = parsed.issued()
        else {
            panic!("a body with only errors is not a certificate");
        };
        assert_eq!(disposition, "no disposition");
        assert!(detail.contains("Invalid-OTP"), "{detail}");
    }

    #[test]
    fn a_request_id_is_a_string_however_it_arrived() {
        let numeric = CsidResponse {
            disposition: Some("ISSUED".to_owned()),
            token: Some("t".to_owned()),
            secret: Some("s".to_owned()),
            request_id: Some(serde_json::json!(1_234_567)),
            errors: None,
        };
        assert_eq!(numeric.issued().expect("issued").request_id, "1234567");

        let text = CsidResponse {
            disposition: Some("ISSUED".to_owned()),
            token: Some("t".to_owned()),
            secret: Some("s".to_owned()),
            request_id: Some(serde_json::json!("1234567")),
            errors: None,
        };
        assert_eq!(text.issued().expect("issued").request_id, "1234567");
    }

    #[test]
    fn the_response_reads_zatcas_field_names() {
        let body = r#"{
            "requestID": 1234567890123,
            "dispositionMessage": "ISSUED",
            "binarySecurityToken": "dG9rZW4=",
            "secret": "c2VjcmV0",
            "errors": null
        }"#;
        let parsed: CsidResponse = serde_json::from_str(body).expect("reads");
        let csid = parsed.issued().expect("issued");
        assert_eq!(csid.token, "dG9rZW4=");
        assert_eq!(csid.secret, "c2VjcmV0");
        assert_eq!(csid.request_id, "1234567890123");
    }

    #[test]
    fn the_bodies_serialise_to_the_names_zatca_reads() {
        let compliance = serde_json::to_value(ComplianceRequest {
            csr: "Q1NS".to_owned(),
        })
        .expect("serialises");
        assert_eq!(compliance["csr"], "Q1NS");

        let production = serde_json::to_value(ProductionRequest {
            compliance_request_id: "1234".to_owned(),
        })
        .expect("serialises");
        assert_eq!(production["compliance_request_id"], "1234");
    }

    #[test]
    fn each_stage_seals_into_its_own_place() {
        assert_eq!(Stage::Compliance.secret_key(), COMPLIANCE_SECRET);
        assert_eq!(Stage::Production.secret_key(), PRODUCTION_SECRET);
        assert_ne!(
            Stage::Compliance.secret_key(),
            Stage::Production.secret_key()
        );
        for stage in Stage::ALL {
            assert_eq!(stage.as_str().parse::<Stage>(), Ok(stage));
        }
    }

    #[test]
    fn a_check_passes_only_when_every_document_did() {
        assert!(
            ComplianceChecks {
                submitted: 6,
                passed: 6,
                failures: vec![],
            }
            .all_passed()
        );
        assert!(
            !ComplianceChecks {
                submitted: 6,
                passed: 5,
                failures: vec![("COMPLIANCE-381-2".to_owned(), vec![])],
            }
            .all_passed(),
            "five of six is not a pass"
        );
        assert!(
            !ComplianceChecks {
                submitted: 0,
                passed: 0,
                failures: vec![],
            }
            .all_passed(),
            "submitting nothing proves nothing"
        );
    }
}
