-- Short links, for anything.
--
-- # Why this is core rather than a module
--
-- It holds no business meaning (D11). A link points at something and counts
-- who followed it; it does not know whether the thing on the other end is a
-- booking, an invoice or a page on somebody else's website. Every module may
-- make one, nobody enables it, and there is nothing about it a tenant would
-- switch on by name — the same argument `0005_numbering.sql` and
-- `0007_occupancy.sql` make.
--
-- # Why it is not a projection
--
-- A read model can be rebuilt; **a link somebody has already been sent cannot
-- be un-issued**. A token in a text message on a customer's phone is a fact
-- about the world, and `rebuild_swap` — which drops and rebuilds `proj_*` —
-- must never come near it. Write-side state, in the migration chain, where the
-- rebuild cannot reach.
--
-- # Why there is a token *and* a key
--
-- They answer different questions. The **key** is the caller's, and it is what
-- makes shortening the same thing twice return the same link rather than two
-- (L8) — a reminder that is retried must not send a customer a second URL. The
-- **token** is what goes in the message, and it is random because a link is
-- often the only thing standing between a stranger and whatever it points at.
--
-- Deriving the token from the key would make it guessable: a key reads
-- `booking.reminder.BK-1041`, and anybody who can guess a booking id could walk
-- the whole diary.

CREATE TABLE IF NOT EXISTS short_link (
    -- What goes in the message. Sixty bits out of a v4 UUID, hex, sixteen
    -- characters — short enough that an SMS billed by length is not paying for
    -- it, and long enough that guessing one is not a strategy.
    --
    -- Generated by the database, not by Rust: this is not the mutation's
    -- identity (that is `key`), so it is not the kind of value law L8 is about,
    -- and a `DEFAULT` keeps the whole insert one statement.
    token          TEXT PRIMARY KEY
                   DEFAULT substr(replace(gen_random_uuid()::text, '-', ''), 1, 16)
                   CHECK (length(token) BETWEEN 8 AND 64),

    -- **The caller's identity for this link.** Shortening the same key twice
    -- gives back the same token, which is what makes a retried reminder one
    -- link rather than two.
    key            TEXT NOT NULL UNIQUE CHECK (length(key) BETWEEN 1 AND 200),

    -- Where it goes. An absolute URL when `external`, otherwise a path inside
    -- this tenant's own API — `/v1/booking/public/reservations/BK-1041`.
    target         TEXT NOT NULL CHECK (length(target) BETWEEN 1 AND 2000),
    external       BOOLEAN NOT NULL DEFAULT false,

    created_at     TIMESTAMPTZ NOT NULL,
    -- **Optional.** Most links outlive anything that would expire them; the
    -- ones that do not are the ones carrying access to something.
    expires_at     TIMESTAMPTZ,
    -- Optional too. A single-use link is how a one-time action — confirm, opt
    -- out, download this export — stops being replayable from a phone somebody
    -- lent to a friend.
    single_use     BOOLEAN NOT NULL DEFAULT false,

    -- The visit record. Counts and the two ends rather than a row per hit: a
    -- link in a marketing message can be followed thousands of times, and an
    -- unbounded table nobody reads is a cost with no reader.
    --
    -- ponytail: per-visit rows (with a user agent and a referrer) when somebody
    -- wants attribution. The columns below are what a person asks for first —
    -- "did they open it, and when" — and they are three integers.
    visits         INTEGER NOT NULL DEFAULT 0 CHECK (visits >= 0),
    first_visit_at TIMESTAMPTZ,
    last_visit_at  TIMESTAMPTZ
);

-- "What have we sent recently", which is the only listing anybody asks for.
CREATE INDEX IF NOT EXISTS short_link_created_idx ON short_link (created_at DESC);
