-- Somebody else resets a second factor, and the account can only enrol again
-- through the link that was mailed.
--
-- ===========================================================================
-- Why the link and the state are two different things
-- ===========================================================================
--
-- `password_reset` is one row that is both the permission and the record of it,
-- and the sweep deletes it an hour later because an expired reset link is
-- rubbish. That shape cannot be copied here.
--
-- A reset takes the factor away, which leaves an account with a password and no
-- factor — exactly the state `0015`'s enrolment hands to whoever enrols first.
-- The rule this closes is that after a reset **only the mailed link may enrol**,
-- and that it keeps holding after the link has expired: if waiting out the hour
-- reopened password-only enrolment, the attacker's move would be to wait.
--
-- So the *fact* is on the account — `identity.second_factor_reset_at`, cleared
-- by a confirmed enrolment and by nothing else — and the *permission* is a row
-- here, which expires and is swept exactly as a password reset is. Sweeping the
-- link therefore takes nothing away: it leaves the account where it was, needing
-- a fresh link, which whoever reset it can send.
--
-- ===========================================================================
-- Why there is no `attempts` column
-- ===========================================================================
--
-- `password_reset.attempts` bounds guessing at the **six digits** the link
-- gates: the token is 256 bits and unguessable, the code behind it is twenty.
-- Nothing is gated behind this link — presenting it is the whole of the
-- permission, and the code that confirms the enrolment is generated by the app
-- the holder is enrolling. There is nothing to guess, so there is nothing to
-- count, and a column nothing increments would be a claim the code does not
-- make.
--
-- What bounds it instead: single use (`used_at`, set when an enrolment
-- completes), an hour of life, and the fact that only a tenant's owner, a member
-- the tenant gave the claim to, or platform support can cause a row at all.

CREATE TABLE second_factor_reset (
    id           UUID PRIMARY KEY,

    -- Never the token, only its SHA-256, for the reason `password_reset`,
    -- `invitation` and `session` all give: a leaked dump holds no working links.
    token_hash   BYTEA NOT NULL UNIQUE CHECK (length(token_hash) = 32),

    -- Whose factor was reset. Pinned when the link is minted, never resolved at
    -- redemption — same argument as `password_reset.identity_id`.
    identity_id  UUID NOT NULL REFERENCES identity (id) ON DELETE CASCADE,

    expires_at   TIMESTAMPTZ NOT NULL,

    -- Set when an enrolment completes, for **every** outstanding row of that
    -- identity: two resets in a row leave two live links, and the account
    -- enrolling once must not leave the other one able to enrol again.
    used_at      TIMESTAMPTZ,

    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- What an enrolment presents a token against, and what a completed enrolment
-- spends.
CREATE INDEX second_factor_reset_identity_idx ON second_factor_reset (identity_id);

-- For the sweep, which does not care about the lifecycle columns.
CREATE INDEX second_factor_reset_expiry_idx ON second_factor_reset (expires_at);

COMMENT ON TABLE second_factor_reset IS
    'One-hour, single-use permission to enrol a second factor, mailed to '
    'somebody whose factor was reset by their company''s owner, by a member '
    'holding hr:reset_second_factor, or by platform support. The account stays '
    'link-only after the row expires — that fact is identity.second_factor_reset_at, '
    'not this row.';

-- **The fact, on the account.** Non-NULL means: somebody else removed this
-- account's second factor, and nothing has been enrolled since. While it is set,
-- `begin_second_factor` and `confirm_second_factor` refuse unless the caller
-- presents a live row above. A confirmed enrolment clears it.
--
-- Nullable and with no default, so an account that never had a factor is
-- untouched: the first-ever enrolment by whoever holds the password stays the
-- accepted gap (Round 3 decision B).
ALTER TABLE identity ADD COLUMN second_factor_reset_at TIMESTAMPTZ;

COMMENT ON COLUMN identity.second_factor_reset_at IS
    'When somebody else reset this account''s second factor. While set, a new '
    'factor can only be enrolled by presenting a live second_factor_reset token; '
    'a confirmed enrolment clears it.';
